### ISSUE TITLE
Switch to Elisa music player & Firefox Developer Edition & Add kodi, Obs-Studio, Minetest ?

### ISSUE THREAD

**Issue by DraGiuS** [netrunner-rolling/manjaro-tools-profile#1]
All in the title, it's a suggestion...

**Comment by NuLogicSystems** [comment]
Individual project Issues are to be used for bug reports and/or official changes only, not for suggestions.
Please use the one for suggestions here: https://github.com/netrunner-rolling/QA-Suggestions
